[project]
name = "nature-bingo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "tabpfn>=9.1.0",
    "torch",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
